server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: local_docker_logs
  docker_sd_configs:
    - host: unix:///var/run/docker.sock
      refresh_interval: 5s
  relabel_configs:
    - source_labels: ['__meta_docker_container_name']
      regex: '/memento_backend'
      target_label: 'job'
      replacement: 'memento_backend'
    - source_labels: ['__meta_docker_container_name']
      regex: '/memento_db'
      target_label: 'job'
      replacement: 'memento_db'
